# MyTurtleProgram.py
# Cooper Cross
# 9/4/19

import turtle
Joe = turtle.Turtle()
wn = turtle.Screen()
wn.bgcolor("sky blue")
Joe.speed (11)

Joe.pencolor("saddlebrown")
Joe.pensize(4)
Joe.fillcolor("azure3")
Joe.begin_fill()
Joe.forward(200)
Joe.right(90)
Joe.forward(250)
Joe.right(90)
Joe.forward(400)
Joe.right(90)
Joe.forward(250)
Joe.right(90)
Joe.forward(200)
Joe.end_fill()

Joe.penup()
Joe.goto(-50,-250)
Joe.pendown()

Joe.left(90)
Joe.forward(125)
Joe.right(90)
Joe.forward(100)
Joe.right(90)
Joe.forward(125)

Joe.penup()
Joe.goto(40,-200)
Joe.pendown()

Joe.pensize(1)
Joe.pencolor("gray1")
Joe.fillcolor("gray85")
Joe.begin_fill()
Joe.circle(2)
Joe.end_fill()
Joe.pensize(4)

Joe.penup()
Joe.goto(-85,-75)
Joe.pendown()

Joe.pencolor("saddlebrown")
Joe.fillcolor("sky blue")
Joe.begin_fill()
Joe.left(180)
Joe.forward(50)
Joe.left(90)
Joe.forward(100)
Joe.left(90)
Joe.forward(100)
Joe.left(90)
Joe.forward(100)
Joe.left(90)
Joe.forward(50)
Joe.left(90)
Joe.forward(100)
Joe.right(90)
Joe.forward(50)
Joe.right(90)
Joe.forward(50)
Joe.right(90)
Joe.forward(100)
Joe.end_fill()

Joe.penup()
Joe.goto(-135,-25)
Joe.pendown()

Joe.pencolor("saddlebrown")
Joe.fillcolor("sky blue")
Joe.begin_fill()
Joe.forward(50)
Joe.right(90)
Joe.forward(50)
Joe.right(90)
Joe.forward(50)
Joe.right(90)
Joe.forward(50)
Joe.end_fill()



Joe.penup()
Joe.goto(135,-125)
Joe.pendown()

Joe.pencolor("saddlebrown")
Joe.fillcolor("sky blue")
Joe.begin_fill()
Joe.right(180)
Joe.forward(50)
Joe.right(90)
Joe.forward(100)
Joe.right(90)
Joe.forward(100)
Joe.right(90)
Joe.forward(100)
Joe.right(90)
Joe.forward(50)
Joe.right(90) 
Joe.forward(100)
Joe.right(90)
Joe.forward(50)
Joe.right(90)
Joe.forward(50)
Joe.right(90)
Joe.end_fill()
Joe.forward(100)

Joe.penup()
Joe.goto(200,0)
Joe.pendown()

Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)
Joe.forward(1)
Joe.right(90)
Joe.forward(1)
Joe.left(90)


Joe.hideturtle()















